name: Log Push Time

on:
  push:
    branches:
      - [main,far]

jobs:
  log-time:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Write push time to file
      run: echo "Push occurred at $(date)" >> time.log

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add time.log
        git commit -m "Log push time"
        git push
