name: Log Push Time

on:
  push:
    branches:
      - far  # شاخه‌ای که می‌خواهید این اکشن برای آن اجرا شود

jobs:
  log-time:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Update time.log with the push timestamp
      run: echo "Push occurred at $(date)" >> time.log

    - name: Configure git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Commit and push changes
      run: |
        git add time.log
        git commit -m "Log push time"
        git push
