name: Update Last Commit Message

on:
  push:
    branches:
      - far

jobs:
  modify-commit-message:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Retrieve the latest commit message
      id: get-message
      run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

    - name: Modify the commit message
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git commit --amend -m "${COMMIT_MESSAGE}*" || echo "No changes to amend."
        git push --force
